<?php

namespace Database\Seeders;

use App\Models\JobVacancy;
use App\Models\User;
use Illuminate\Database\Seeder;

class JobVacancySeeder extends Seeder
{
    public function run(): void
    {
        $companyA = User::query()->where('email', 'mitra.company.a@kompeta.test')->firstOrFail();
        $companyB = User::query()->where('email', 'mitra.company.b@kompeta.test')->firstOrFail();
        $umkmA = User::query()->where('email', 'mitra.umkm.a@kompeta.test')->firstOrFail();
        $umkmB = User::query()->where('email', 'mitra.umkm.b@kompeta.test')->firstOrFail();

        $vacancies = [
            [
                'slug' => 'accounting-staff-1602be',
                'mitra_user_id' => $companyA->id,
                'position_name' => 'Accounting Staff',
                'category' => 'Keuangan',
                'job_type' => JobVacancy::JOB_TYPE_FULL_TIME,
                'work_policy' => JobVacancy::WORK_POLICY_OFFICE,
                'experience_level' => JobVacancy::EXPERIENCE_LESS_THAN_ONE_YEAR,
                'province' => 'DKI Jakarta',
                'salary_min' => 5700000,
                'salary_max' => 5800000,
                'is_salary_hidden' => false,
                'requirements' => "Minimal Sarjana (S1).\nMemahami MYOB.\nKomunikasi baik.",
                'job_description' => 'Mengerjakan proses jurnal, rekonsiliasi, dan laporan keuangan harian perusahaan.',
                'is_published' => true,
                'created_at' => now()->subHours(5),
                'updated_at' => now()->subHours(5),
                'skills' => ['MYOB', 'Excel', 'Akuntansi Dasar'],
                'benefits' => ['BPJS Kesehatan', 'BPJS Ketenagakerjaan', 'Makan Siang'],
            ],
            [
                'slug' => 'security-freelance-jakarta',
                'mitra_user_id' => $companyA->id,
                'position_name' => 'Security Freelance',
                'category' => 'Keamanan',
                'job_type' => JobVacancy::JOB_TYPE_FREELANCE,
                'work_policy' => JobVacancy::WORK_POLICY_OFFICE,
                'experience_level' => JobVacancy::EXPERIENCE_NO_EXPERIENCE,
                'province' => 'DKI Jakarta',
                'salary_min' => null,
                'salary_max' => null,
                'is_salary_hidden' => true,
                'requirements' => "Minimal SMA/SMK.\nBersedia kerja shift.",
                'job_description' => 'Menjaga keamanan area kantor dan melakukan patroli berkala.',
                'is_published' => true,
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
                'skills' => ['Office Security', 'Hotel Security'],
                'benefits' => ['Uang Makan', 'Seragam Kerja'],
            ],
            [
                'slug' => 'data-entry-operator-bandung',
                'mitra_user_id' => $companyB->id,
                'position_name' => 'Data Entry Operator',
                'category' => 'Administrasi',
                'job_type' => JobVacancy::JOB_TYPE_CONTRACT,
                'work_policy' => JobVacancy::WORK_POLICY_HYBRID,
                'experience_level' => JobVacancy::EXPERIENCE_FRESH_GRADUATE,
                'province' => 'Jawa Barat',
                'salary_min' => 4200000,
                'salary_max' => 5000000,
                'is_salary_hidden' => false,
                'requirements' => "Minimal D3 semua jurusan.\nTeliti dan cepat mengetik.",
                'job_description' => 'Input, validasi, dan sinkronisasi data operasional klien setiap hari.',
                'is_published' => true,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
                'skills' => ['Data Entry', 'Google Sheets', 'Administrasi'],
                'benefits' => ['Asuransi Kesehatan', 'Laptop Kerja'],
            ],
            [
                'slug' => 'junior-qa-tester-remote',
                'mitra_user_id' => $companyB->id,
                'position_name' => 'Junior QA Tester',
                'category' => 'Teknologi',
                'job_type' => JobVacancy::JOB_TYPE_FULL_TIME,
                'work_policy' => JobVacancy::WORK_POLICY_REMOTE,
                'experience_level' => JobVacancy::EXPERIENCE_FRESH_GRADUATE,
                'province' => 'Jawa Barat',
                'salary_min' => 5000000,
                'salary_max' => 6500000,
                'is_salary_hidden' => false,
                'requirements' => "Mengerti dasar software testing.\nMampu membuat test case.",
                'job_description' => 'Menguji fitur aplikasi web dan mobile serta menuliskan bug report.',
                'is_published' => true,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(4),
                'skills' => ['Manual Testing', 'Test Case Writing', 'Postman'],
                'benefits' => ['Remote Allowance', 'Learning Budget'],
            ],
            [
                'slug' => 'baker-assistant-semarang',
                'mitra_user_id' => $umkmA->id,
                'position_name' => 'Baker Assistant',
                'category' => 'Produksi',
                'job_type' => JobVacancy::JOB_TYPE_PART_TIME,
                'work_policy' => JobVacancy::WORK_POLICY_OFFICE,
                'experience_level' => JobVacancy::EXPERIENCE_NO_EXPERIENCE,
                'province' => 'Jawa Tengah',
                'salary_min' => 2200000,
                'salary_max' => 3000000,
                'is_salary_hidden' => false,
                'requirements' => "Menyukai pekerjaan dapur.\nSiap kerja pagi.",
                'job_description' => 'Membantu persiapan adonan, oven, dan kemasan produk roti harian.',
                'is_published' => true,
                'created_at' => now()->subHours(10),
                'updated_at' => now()->subHours(6),
                'skills' => ['Food Preparation', 'Packing'],
                'benefits' => ['Makan Harian', 'Bonus Penjualan'],
            ],
            [
                'slug' => 'content-creator-umkm-semarang',
                'mitra_user_id' => $umkmA->id,
                'position_name' => 'Content Creator Produk UMKM',
                'category' => 'Pemasaran',
                'job_type' => JobVacancy::JOB_TYPE_FREELANCE,
                'work_policy' => JobVacancy::WORK_POLICY_REMOTE,
                'experience_level' => JobVacancy::EXPERIENCE_LESS_THAN_ONE_YEAR,
                'province' => 'Jawa Tengah',
                'salary_min' => 1500000,
                'salary_max' => 3500000,
                'is_salary_hidden' => false,
                'requirements' => "Memiliki portofolio konten pendek.\nPaham tren media sosial.",
                'job_description' => 'Membuat konten foto/video produk untuk kebutuhan marketplace dan media sosial.',
                'is_published' => true,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
                'skills' => ['Copywriting', 'Canva', 'Video Editing'],
                'benefits' => ['Jam Kerja Fleksibel', 'Insentif KPI'],
            ],
            [
                'slug' => 'operator-produksi-kayu-jogja',
                'mitra_user_id' => $umkmB->id,
                'position_name' => 'Operator Produksi Kerajinan',
                'category' => 'Produksi',
                'job_type' => JobVacancy::JOB_TYPE_CONTRACT,
                'work_policy' => JobVacancy::WORK_POLICY_OFFICE,
                'experience_level' => JobVacancy::EXPERIENCE_NO_EXPERIENCE,
                'province' => 'DI Yogyakarta',
                'salary_min' => 2600000,
                'salary_max' => 3400000,
                'is_salary_hidden' => false,
                'requirements' => "Mampu menggunakan alat kerja sederhana.\nTelaten dan rapi.",
                'job_description' => 'Mengolah material kayu, finishing produk, dan quality check sebelum pengiriman.',
                'is_published' => true,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(5),
                'skills' => ['Woodworking', 'Finishing'],
                'benefits' => ['Transport Allowance', 'Lembur Berbayar'],
            ],
            [
                'slug' => 'magang-admin-marketplace-jogja',
                'mitra_user_id' => $umkmB->id,
                'position_name' => 'Magang Admin Marketplace',
                'category' => 'Administrasi',
                'job_type' => JobVacancy::JOB_TYPE_INTERNSHIP,
                'work_policy' => JobVacancy::WORK_POLICY_HYBRID,
                'experience_level' => JobVacancy::EXPERIENCE_FRESH_GRADUATE,
                'province' => 'DI Yogyakarta',
                'salary_min' => 1000000,
                'salary_max' => 1500000,
                'is_salary_hidden' => false,
                'requirements' => "Minimal SMA/SMK.\nPaham dasar marketplace.",
                'job_description' => 'Membantu upload produk, optimasi deskripsi, dan respon chat pembeli.',
                'is_published' => true,
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(10),
                'skills' => ['Marketplace Management', 'Customer Service'],
                'benefits' => ['Sertifikat Magang', 'Mentoring'],
            ],
            [
                'slug' => 'staff-riset-produk-freelance',
                'mitra_user_id' => $companyB->id,
                'position_name' => 'Staff Riset Produk',
                'category' => 'Riset',
                'job_type' => JobVacancy::JOB_TYPE_FREELANCE,
                'work_policy' => JobVacancy::WORK_POLICY_HYBRID,
                'experience_level' => JobVacancy::EXPERIENCE_LESS_THAN_ONE_YEAR,
                'province' => 'DKI Jakarta',
                'salary_min' => 3000000,
                'salary_max' => 4500000,
                'is_salary_hidden' => false,
                'requirements' => "Terbiasa analisis data ringan.\nKomunikatif.",
                'job_description' => 'Mendukung tim produk dalam riset pengguna dan validasi ide fitur.',
                'is_published' => true,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'skills' => ['User Research', 'Spreadsheet', 'Interview'],
                'benefits' => ['Flexible Hours', 'Project Bonus'],
            ],
            [
                'slug' => 'backend-intern-internal',
                'mitra_user_id' => $companyA->id,
                'position_name' => 'Backend Intern Internal',
                'category' => 'Teknologi',
                'job_type' => JobVacancy::JOB_TYPE_INTERNSHIP,
                'work_policy' => JobVacancy::WORK_POLICY_REMOTE,
                'experience_level' => JobVacancy::EXPERIENCE_FRESH_GRADUATE,
                'province' => 'DKI Jakarta',
                'salary_min' => 1500000,
                'salary_max' => 2000000,
                'is_salary_hidden' => false,
                'requirements' => "Memahami dasar API.\nMampu menggunakan Git.",
                'job_description' => 'Program magang internal untuk support pengembangan backend.',
                'is_published' => false,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subHours(12),
                'skills' => ['PHP', 'Laravel', 'Git'],
                'benefits' => ['Mentoring Tim', 'Sertifikat'],
            ],
        ];

        foreach ($vacancies as $item) {
            $vacancy = JobVacancy::query()->updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'mitra_user_id' => $item['mitra_user_id'],
                    'position_name' => $item['position_name'],
                    'category' => $item['category'],
                    'job_type' => $item['job_type'],
                    'work_policy' => $item['work_policy'],
                    'experience_level' => $item['experience_level'],
                    'province' => $item['province'],
                    'salary_min' => $item['salary_min'],
                    'salary_max' => $item['salary_max'],
                    'is_salary_hidden' => $item['is_salary_hidden'],
                    'requirements' => $item['requirements'],
                    'job_description' => $item['job_description'],
                    'is_published' => $item['is_published'],
                    'created_at' => $item['created_at'],
                    'updated_at' => $item['updated_at'],
                ]
            );

            $vacancy->skills()->delete();
            $vacancy->benefits()->delete();

            foreach ($item['skills'] as $skill) {
                $vacancy->skills()->create(['name' => $skill]);
            }

            foreach ($item['benefits'] as $benefit) {
                $vacancy->benefits()->create(['name' => $benefit]);
            }
        }
    }
}
